[project]
name = "q-map"
r_version = ">=4.6.0"

[dependencies]
dplyr = "*"
httr = "*"
jsonlite = "*"
purrr = "*"
readr = "*"
readxl = "*"
rmapshaper = "*"
sf = "*"
tarchetypes = "*"
targets = "*"
tibble = "*"
tidyr = "*"
